"""tables creation

Revision ID: d5ce1cd33541
Revises: 
Create Date: 2024-02-17 22:34:15.643181

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d5ce1cd33541"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "currencies",
        sa.Column("code", sa.String(length=3), nullable=False),
        sa.Column("full_name", sa.String(length=50), nullable=False),
        sa.Column("sign", sa.String(length=3), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "exchangerates",
        sa.Column("base_currency_id", sa.Integer(), nullable=False),
        sa.Column("target_currency_id", sa.Integer(), nullable=False),
        sa.Column("rate", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["base_currency_id"],
            ["currencies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_currency_id"],
            ["currencies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("exchangerates")
    op.drop_table("currencies")
    # ### end Alembic commands ###
