"""add unique constraint

Revision ID: 1898d75792ec
Revises: 371d1d72a3ba
Create Date: 2024-02-23 21:14:58.976149

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1898d75792ec"
down_revision: Union[str, None] = "371d1d72a3ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "exchangerates", ["base_currency_id", "target_currency_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "exchangerates", type_="unique")
    # ### end Alembic commands ###
